import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to online code editor.
        </h1>

        <p className={styles.description}>
        </p>

        <div className={styles.grid}>
          <a href="/manager/ContainerList" className={styles.card}>
            <h2>应用列表 &rarr;</h2>
            <p>在这里查看访问管理所有应用</p>
          </a>

          <a href="/manager/ContainerCreate" className={styles.card}>
            <h2>创建新应用 &rarr;</h2>
            <p>创建新应用</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        Powered by next.js and dockeronde.
      </footer>
    </div>
  )
}

export default Home
