# 用于添加本地deb安装, 方便调试使用
FROM node:16

EXPOSE 80 8080
ENV PORT 8080
ENV CODE_VERSION 3.3.1
WORKDIR /code-server
COPY ./config.yaml ./
# COPY ./sources.list /etc/apt
COPY ./entrypoint.sh ./
ADD ./code-server_${CODE_VERSION}_amd64.deb ./
RUN dpkg -i code-server_${CODE_VERSION}_amd64.deb

ENTRYPOINT ["/code-server/entrypoint.sh"]
CMD ["https://github.com/alanwei43/next-project.git"]